- name: watermelon
  description: A brand new default theme for Hexo.
  link: https://github.com/shaunabanana/hexo-theme-watermelon
  preview: https://shengchen.design
  tags:
    - dynamic
    - responsive
    - two_column
    - monospace

  update_items:
    - project
    - news
    - blog
