- name: watermelon
  description: A brand new default theme for Hexo.
  link: https://github.com/hexojs/hexo-theme-landscape
  preview: http://hexo.io/hexo-theme-landscape
  tags:
    - dynamic
    - responsive
    - widget
    - two_column

  update_items:
    - project
    - news
    - blog
